import Head from "next/head";
import Image from "next/image";

import avatarPic from "../../public/luna-avatar.jpg";
import studioLogo from "../../public/731-logo.jpg";
import instLogo from "../../public/inst-logo.png";

import styles from "../styles/Home.module.css";

export default function Home({ instagramPosts }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Lunar Toy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Image
          className={styles.avatar}
          src={avatarPic}
          alt="Picture of the toy poodle"
          width={150}
          height={150}
        />
        <h1 className={styles.title}>Hello! My name is Lúna!</h1>

        <h2 className={styles.description}>I'm toy poodle from Russia!</h2>
        <p className={styles.actionText}>Let's check my links!</p>

        <div className={styles.grid}>
          <a
            rel="noreferrer"
            target="_blank"
            href="https://www.instagram.com/lunar.toy/"
            className={styles.card}
          >
            <Image src={instLogo} />
            <div className={styles.cardBody}>
              <p className={styles.cardTitle}>My Instagram</p>
              <p className={styles.cardText}>@lunar.toy</p>
            </div>
          </a>

          <a
            rel="noreferrer"
            target="_blank"
            href="https://www.instagram.com/731.studio/"
            className={styles.card}
          >
            <Image src={studioLogo} />
            <div className={styles.cardBody}>
              <p className={styles.cardTitle}>My business</p>
              <p className={styles.cardText}>@731.studio</p>
            </div>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <p>
          Powered by{" "}
          <a
            href="https://www.instagram.com/rinarunaan/"
            rel="noreferrer"
            target="_blank"
          >
            {" mom"}
          </a>
        </p>
      </footer>
    </div>
  );
}
