import Head from "next/head";
import Image from "next/image";

import InstagramFeed from "../components/instagramFeed";
import avatarPic from "../../public/luna-avatar.jpg";

import styles from "../styles/Home.module.css";

export default function Home({ instagramPosts }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Lunar Toy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Image
          className={styles.avatar}
          src={avatarPic}
          alt="Picture of the toy poodle"
          width={150}
          height={150}
        />
        <h1 className={styles.title}>Hello! My name is Lúna!</h1>

        <h2 className={styles.description}>I'm toy poodle!</h2>
        <p>Let's check my links!</p>

        <div className={styles.grid}>
          <a
            href="https://www.instagram.com/lunar.toy/"
            className={styles.card}
          >
            <h2>Instagram &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>
        </div>
      </main>
      <InstagramFeed />

      <footer className={styles.footer}>
        <p>
          Powered by{" "}
          <a
            href="https://www.instagram.com/rinarunaan/"
            rel="noreferrer"
            target="_blank"
          >
            {" mom"}
          </a>
        </p>
      </footer>
    </div>
  );
}
